name: FUNCTION_APP
on:  
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'function' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: 'func-ai-recruiter-dev'
          path: |
            release.zip
            !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: 'func-ai-recruiter-dev'

      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'nuf-referralai-dev-wus3-fn-01'
          slot-name: 'app'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{secrets.FUNCTION_APP}}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
